FROM node:18.12.1

RUN apt update
RUN apt upgrade -y
RUN apt-get install git
RUN git clone https://github.com/hervouetdylan/e-elan.git

# installe les dépendances du projet
RUN npm install
# construit l'app pour la production en la minifiant
CMD [ "npm", "run", "serve" ]